### ISSUE TITLE
Не работает авторизация через VK

### ISSUE THREAD

**Issue by realdigger** [ulogin/ulogin-SMF#4]

**Comment by realdigger** [comment]
Выдает
{"error":"invalid_request","error_description":"Security Error"}

**Comment by ipshenicyn** [comment]
К плагину этот вопрос не имеет отношения. 
Очистите куки ВК и ошибка пройдет. 
Подробности здесь: [http://ulogin.reformal.ru/proj/?ia=497401](url)
